### ISSUE TITLE
Author field empty in package.json

### ISSUE THREAD

**Issue by Jameskmonger** [faxioman/outlinejs#2]
Hi @faxioman,

Your `author` field is empty in `package.json`; most authors try to fill this in with their name, domain and email address.

**Comment by faxioman** [comment]
Hi @Jameskmonger !
Why not ;)
I have added the author field.

**Comment by Jameskmonger** [comment]
How else are you going to get famous, @faxioman? :stuck_out_tongue_closed_eyes:
